### ISSUE TITLE
Howto Setup Docker container to run sarpy_apps

### ISSUE THREAD

**Issue by AshitakaLax** [ngageoint/sarpy_apps#57]
Hi, I've loved using the image_viewer and have it setup for my local machine (which took a bit of messing with).
I would like to share it with others, so I'm trying to add it to a rocky85 docker image. I'm sure I have done something wrong but would like the guidance. Note: I know I can render UI elements in this docker container since I have done with other applications(x11).

I have roughly the following.

```dockerfile
RUN dnf install -y python3-tkinter
# this is where things breakdown a bit
# I've tried
RUN pip3 install -q numpy matplotlib Pillow plotly sarpy tk_builder
# also tried without the above install the following in the sarpy_apps directory
RUN python3 -m pip install .
# and the following
RUN python3 setup.py install
```

Everytime i run it I still get 

```bash
$ python3 sarpy_apps/apps/image_viewer.py 
Traceback (most recent call last):
  File "/bpvol/sarpy_apps-master/sarpy_apps/apps/image_viewer.py", line 11, in <module>
    import tkinter
ModuleNotFoundError: No module named 'tkinter'
```
Any guidance or sample dockerfile would be appreciated.
Thanks

**Comment by bombaci-vsc** [comment]
The error suggests `tkinter` isn't installed in your docker image's python environment.  I don't believe this is caused by anything `sarpy_apps` is doing.  

This is likely a result of how your python environment is being constructed, either by something in your base image or elsewhere in your Dockerfile.  

I was not able to reproduce your error with this `Dockerfile`:

```
FROM rockylinux:8.5

RUN dnf install -y python3 python3-tkinter python3-pip
RUN dnf install -y gcc zlib-devel libjpeg-devel python3-devel  # needed by Pillow
COPY sarpy_apps /sarpy_apps
WORKDIR /sarpy_apps
RUN pip3 install .

```

Then when running it I get an expected DISPLAY error, but this happens after it successfully imports `tkinter`.

```
# python3 -m sarpy_apps.apps.image_viewer                                                                                      
Traceback (most recent call last):                                                                                                                           
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/sarpy_apps/sarpy_apps/apps/image_viewer.py", line 259, in <module>
    main(reader=args.input)
  File "/sarpy_apps/sarpy_apps/apps/image_viewer.py", line 237, in main
    root = tkinter.Tk()
  File "/usr/lib64/python3.6/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

**Comment by AshitakaLax** [comment]
Sorry for the long delay. I'll give these updates a shot and post back.

**Comment by petersontex** [comment]
> Sorry for the long delay. I'll give these updates a shot and post back.

Hello @AshitakaLax, Were you able to test the steps above? Did this resolve your issue?

**Comment by petersontex** [comment]
No response from end user. Closing this issue.

**Comment by AshitakaLax** [comment]
@petersontex Sounds good, Sorry I haven't gotten to this.
I've been busy with other efforts, and this hasn't been a priority. I'm sure sometime long down the road I'll get back to this.
Whenever I get back, I'll come back to this and share my updates. Closing the issue should be good for me.

**Comment by petersontex** [comment]
> [@petersontex](https://github.com/petersontex) Sounds good, Sorry I haven't gotten to this. I've been busy with other efforts, and this hasn't been a priority. I'm sure sometime long down the road I'll get back to this. Whenever I get back, I'll come back to this and share my updates. Closing the issue should be good for me.

@AshitakaLax Excellent! Thank you! Good luck with your other efforts. I look forward to your feedback whenever you are able to get back to working with sarpy_apps in Docker.
